#!/bin/bash

# This file is a pre_build Docker Hub hook that requires a build rule with the following configuration:
#
# Dockerfile location: Dockerfile
# Build Context: codedx-tomcat
#

echo "The pre_build hook is using DOCKER_TAG tag $DOCKER_TAG"

docker run --privileged \
  -v $(pwd):/src \
  -w /src \
  -v /var/run/docker.sock:/var/run/docker.sock \
  bash:5.0.11 \
  /usr/local/bin/bash /src/hooks/pre_build_script $DOCKER_TAG

